### ISSUE TITLE
What is the id of the download in the operation "get dowload?

### ISSUE THREAD

**Issue by RubenCantareroNavarro** [mulesoft/git-connector#2]
Please.

**Comment by josesahad** [comment]
Hi!
are you talking about the getDownload operation from the [GitHub connector](https://github.com/mulesoft/github-connector)?
These are the GitHub docs for [Download Service](http://developer.github.com/v3/repos/downloads/). If you're trying to get a file from GitHub you can use the [get-file-content operation](http://mulesoft.github.io/github-connector/mule/github-config.html#get-file-content).

HTH
José
